---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ansible/syncthing/SyncDirectory:/var/syncthing
    ports:
      - 18384:8384 # Web UI
      - 22100:22000/tcp # TCP file transfers
      - 22100:22000/udp # QUIC file transfers
      - 21127:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
