
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
