apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ldap
  namespace: default
spec:
  selector:
    app: lldap
  ports:
    - port: 3890
      targetPort: 3890
      nodePort: 31001
  type: NodePort
