apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ldap-management
  namespace: default
spec:
  selector:
    app: lldap
  ports:
    - port: 17170
      targetPort: 17170
      nodePort: 31002
  type: NodePort
